### ISSUE TITLE
Shuffle function for List wanted?

### ISSUE THREAD

**Issue by hoelzro** [elm-community/random-extra#5]
Hi there,

I noticed that while there's a shuffle function for `Array`, I didn't see one for `List`.  I've been sharing a [gist](https://gist.github.com/hoelzro/a49d796f2812714ec371) I wrote that provides a list shuffling implemention with users on Slack, but I could clean it up and add it to Random.Extra.  Is this something you'd be interested in?

**Comment by mgold** [comment]
Duping to #4.
