### ISSUE TITLE
upgrade to elm 0.18

### ISSUE THREAD

**Issue by tcoopman** [elm-community/random-extra#6]
I ran elm-upgrade on my program and saw this:

```
WARNING! 1 of your dependencies have not yet been upgraded to 
support Elm 0.18. You can create an issue to request the packages be 
upgraded here:
  - https://github.com/elm-community/random-extra/issues
```

I'll try to create a PR myself

**Comment by jvoigtlaender** [comment]
Look: https://github.com/elm-community/random-extra/tree/update-0.18

:smile:

**Comment by tcoopman** [comment]
@jvoigtlaender woops.
Could it be though that it's not yet visible on elm-packages? http://package.elm-lang.org/packages/elm-community/random-extra/latest points to 1.0.0

**Comment by jvoigtlaender** [comment]
Yes. But I'm sure @mgold will do an `elm-package publish` at the earliest possible moment for him. I think he did publish it to the temporarily set up package site for 0.18 testing during the beta phase. Now he has to do it again for the actual package site after its going live with 0.18 capabilities last night. He will.

**Comment by tcoopman** [comment]
ah ok, I'll wait for it then :+1: 
Thanks!

**Comment by mgold** [comment]
I didn't run the publish command but it's fine how it is. These transitions are always wonky for a few days...
