### ISSUE TITLE
Provide code sample for `person` for Random.Extra.andMap

### ISSUE THREAD

**Issue by EverybodyKurts** [elm-community/random-extra#8]
First, thank you for the hard work and time y'all put in to the this package and thank you for taking the time to consider & respond to this issue.

In the code sample for [Random.Extra.andMap](http://package.elm-lang.org/packages/elm-community/random-extra/2.0.0/Random-Extra#andMap), the code sample references `person` but doesn't explicitly define `person`. I know that it's probably a type alias somewhere but I don't know if it's an already existing `person` record or if it's supposed to be a `Person` constructor.

**Comment by mgold** [comment]
The example in question:

```elm
    randomPerson : Generator Person
    randomPerson =
      map person genFirstName
        |> andMap genLastName
        |> andMap genBirthday
        |> andMap genPhoneNumber
        |> andMap genAddress
        |> andMap genEmail
```

I had always thought of this as a big type alias of a record, with either strings or special date and phone number and address types. That part isn't important so much as, hey look at all the generators we can chain!

That said, I was surprised to find `person` and not `Person`, which would do a better job of implying a record. Would that help?

**Comment by EverybodyKurts** [comment]
Yes, I think that would help.
